name: basic-github-actions
on: [push]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Install docker
        run: sudo apt install docker
        shell: bash

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          cd bin
          ./build.sh
        shell: bash
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Build docker image
        run: |
          cd bin
          ./build.sh
        shell: bash
      - name: Run examples
        run: |
          cd examples
          ls -laF
          cd OASIS_TOSCA_1.2
          ./run.sh
          cd ../OpenStack
          ./run.sh
        shell: bash
    

